"""Counterfactual rationale-stability objective (manuscript S4.6.3).

Manuscript specification
------------------------
* Applied to the LoRA-adapted Stage 2 rationale language model.
* Purpose: structured rationales must change when their supporting evidence
  changes and stay stable when unrelated evidence is unchanged.
* For each review-band training example, exactly one label-preserving
  counterfactual is generated by modifying one admissible evidence element:
  a numerical relation, temporal count, categorical value, entity reference, or
  temporally valid graph relation.
* The fraud label, protected attributes, immutable identifiers and chronological
  split membership remain unchanged.
* Claims directly affected by the change are updated or removed; claims
  supported by unchanged evidence keep their original structured form and
  evidence references.
* The rationale-side probability is regularised so a label-preserving
  modification does not cause an unsupported change in the predicted
  probability.
* Final weight 0.25, selected from {0.25, 0.50, 0.75, 1.00}.
* Counterfactual examples are generated only from the training partition and are
  never added to the test sets or the test-time retrieval pool.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Iterable, Sequence

import numpy as np

from vrfraudnet.errors import LeakageError

#: Evidence elements a counterfactual may modify (manuscript S4.6.3).
ADMISSIBLE_MODIFICATIONS: tuple[str, ...] = (
    "numeric_relation",
    "temporal_count",
    "categorical_value",
    "entity_reference",
    "graph_relation",
)

#: Fields that must never be modified by a counterfactual (manuscript S4.6.3).
IMMUTABLE_FIELDS: tuple[str, ...] = (
    "label",
    "protected_attributes",
    "immutable_identifiers",
    "split_membership",
)


@dataclass
class CounterfactualExample:
    """One label-preserving counterfactual and the claim edits it implies."""

    source_id: str
    modified_field: str
    modification_kind: str
    original_value: Any
    counterfactual_value: Any
    claims_updated: list[int]
    claims_removed: list[int]
    partition: str = "train"

    def __post_init__(self) -> None:
        if self.modification_kind not in ADMISSIBLE_MODIFICATIONS:
            raise ValueError(
                f"{self.modification_kind!r} is not an admissible counterfactual "
                f"modification; expected one of {ADMISSIBLE_MODIFICATIONS}"
            )
        if self.partition != "train":
            raise LeakageError(
                "counterfactual examples may only be generated from the training "
                f"partition (manuscript S4.6.3); got partition={self.partition!r}"
            )
        if self.modified_field in IMMUTABLE_FIELDS:
            raise ValueError(f"{self.modified_field!r} is immutable under S4.6.3")


def generate_counterfactual(
    evidence: dict[str, Any],
    claims: Sequence[dict[str, Any]],
    *,
    rng: np.random.Generator,
    partition: str,
    mutable_fields: Iterable[str] | None = None,
) -> tuple[dict[str, Any], CounterfactualExample]:
    """Produce one label-preserving counterfactual evidence dictionary.

    Exactly one admissible evidence element is modified, as the manuscript
    specifies. Claims that reference the modified field are marked for update;
    claims whose evidence is untouched keep their original form and references.
    """
    if partition != "train":
        raise LeakageError(
            f"refusing to build a counterfactual from the {partition!r} partition"
        )

    candidates = [
        key
        for key in (mutable_fields if mutable_fields is not None else evidence)
        if key in evidence and key not in IMMUTABLE_FIELDS
    ]
    if not candidates:
        raise ValueError("no admissible evidence field available for modification")

    field = str(rng.choice(candidates))
    original = evidence[field]
    modified, kind = _perturb_value(original, rng)

    counterfactual_evidence = dict(evidence)
    counterfactual_evidence[field] = modified

    updated, removed = [], []
    for i, claim in enumerate(claims):
        if claim.get("field") == field or claim.get("evidence_id") == field:
            # A numeric claim can be restated against the new value; a claim
            # whose primitive no longer applies is removed rather than silently
            # left pointing at stale evidence.
            if claim.get("type") == "numeric_comparison":
                updated.append(i)
            else:
                removed.append(i)

    example = CounterfactualExample(
        source_id=str(evidence.get("transaction_id", "unknown")),
        modified_field=field,
        modification_kind=kind,
        original_value=original,
        counterfactual_value=modified,
        claims_updated=updated,
        claims_removed=removed,
        partition=partition,
    )
    return counterfactual_evidence, example


def _perturb_value(value: Any, rng: np.random.Generator) -> tuple[Any, str]:
    """Perturb a single evidence value, returning the new value and its kind."""
    if isinstance(value, bool):
        return (not value), "categorical_value"
    if isinstance(value, (int, np.integer)):
        delta = int(rng.integers(1, 4))
        return int(value) + delta, "temporal_count"
    if isinstance(value, (float, np.floating)):
        scale = 1.0 + float(rng.uniform(0.10, 0.50)) * (1 if rng.random() < 0.5 else -1)
        return float(value) * scale, "numeric_relation"
    if isinstance(value, str):
        return value + "_cf", "entity_reference"
    if isinstance(value, (list, tuple)):
        return list(value)[:-1] if len(value) > 1 else list(value) + ["cf_node"], "graph_relation"
    raise TypeError(f"no counterfactual perturbation defined for value of type {type(value)}")


def rationale_stability_penalty(
    original_probability: float,
    counterfactual_probability: float,
    *,
    evidence_changed: bool,
    tolerance: float = 0.05,
) -> float:
    """Penalty term regularising the rationale-side probability (S4.6.3).

    When the modification is label-preserving *and* the affected evidence does
    not support the prediction, the rationale-side probability should not move
    by more than ``tolerance``. When the modification does touch supporting
    evidence, movement is expected and is not penalised.
    """
    if evidence_changed:
        return 0.0
    drift = abs(float(original_probability) - float(counterfactual_probability))
    return float(max(0.0, drift - tolerance) ** 2)


def counterfactual_loss(
    base_loss: float,
    stability_terms: Sequence[float],
    *,
    weight: float = 0.25,
) -> float:
    """Combine the schema-constrained generation loss with the stability term.

    ``weight`` is the manuscript's final counterfactual-loss weight, 0.25
    (S4.6.3, S4.6.4).
    """
    if not 0.0 <= weight <= 1.0:
        raise ValueError("counterfactual weight must lie in [0, 1]")
    penalty = float(np.mean(stability_terms)) if len(stability_terms) else 0.0
    return float(base_loss + weight * penalty)


def make_counterfactual_batch(
    examples: Sequence[dict[str, Any]],
    claim_lookup: Callable[[dict[str, Any]], Sequence[dict[str, Any]]],
    *,
    rng: np.random.Generator,
    partition: str = "train",
) -> list[tuple[dict[str, Any], CounterfactualExample]]:
    """Generate exactly one counterfactual per input example (manuscript S4.6.3)."""
    return [
        generate_counterfactual(ex, claim_lookup(ex), rng=rng, partition=partition)
        for ex in examples
    ]
