"""End-to-end smoke demo on SYNTHETIC data.

    python examples/run_minimal_demo.py

WHAT THIS IS
------------
A runnable demonstration that the Stage 1 -> Stage 3 -> Stage 4 machinery works:
triage, threshold routing, deterministic verification of a structured rationale,
isotonic mixing and split-conformal calibration.

WHAT THIS IS NOT
----------------
It is **not** a reproduction of any manuscript result, and the numbers it prints
have no scientific meaning whatsoever. The data is generated by
``numpy.random``. No output of this script may be quoted as a VR-FraudNet
result. Reproducing the manuscript requires the five real datasets; see
docs/DATA_AVAILABILITY.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from vrfraudnet.determinism import set_global_seed
from vrfraudnet.evaluation.metrics import compute_all, select_operating_threshold
from vrfraudnet.models.grammar import GrammarSpec, RationaleGrammar
from vrfraudnet.models.stage1_triage import ThresholdGate, TriageClassifier, TriageParams
from vrfraudnet.models.stage4_calibration import (
    IsotonicMixer,
    MixerInputs,
    SplitConformalCalibrator,
)
from vrfraudnet.verifier import DeterministicVerifier, GraphEvidence, TransactionEvidence

BANNER = "=" * 78


def synthetic_dataset(n: int = 12_000, n_features: int = 20, prevalence: float = 0.02):
    """Generate a chronologically ordered synthetic stream. NOT a benchmark."""
    rng = np.random.default_rng(0)
    x = rng.normal(size=(n, n_features))
    weights = rng.normal(scale=0.6, size=n_features)
    logits = x @ weights - 3.2
    probability = 1.0 / (1.0 + np.exp(-logits))
    y = (rng.uniform(size=n) < probability * (prevalence / probability.mean())).astype(int)
    times = np.sort(rng.uniform(0, 1_000_000, size=n))
    return x, y, times


def main() -> int:
    set_global_seed(42)
    print(BANNER)
    print("VR-FraudNet minimal demo  --  SYNTHETIC DATA, NOT A MANUSCRIPT RESULT")
    print(BANNER)

    x, y, _ = synthetic_dataset()
    n = x.shape[0]
    train, valid, calib, test = (
        slice(0, int(0.6 * n)),
        slice(int(0.6 * n), int(0.7 * n)),
        slice(int(0.7 * n), int(0.8 * n)),
        slice(int(0.8 * n), n),
    )
    print(f"\nsynthetic stream: n={n}, prevalence={y.mean():.4%}")

    # ---- Stage 1: triage -------------------------------------------------
    triage = TriageClassifier(TriageParams(n_estimators=120, num_threads=2), seed=42)
    triage.fit(x[train], y[train], x[valid], y[valid])
    p_valid, p_calib, p_test = (
        triage.predict_proba(x[valid]),
        triage.predict_proba(x[calib]),
        triage.predict_proba(x[test]),
    )

    gate = ThresholdGate(0.20, 0.80)
    print(f"Stage 1 routing gate T_low={gate.t_low} T_high={gate.t_high}")
    print(f"  escalation rate on test: {gate.escalation_rate(p_test):.4f}")

    # ---- Stage 3: deterministic verification -----------------------------
    verifier = DeterministicVerifier()
    evidence = TransactionEvidence.from_row(
        "TX-DEMO",
        timestamp=1_000.0,
        numeric={"amount": 9500.0},
        categorical={"payment_type": "wire"},
        entities={"beneficiary": "ACC-88231", "counterparty": "ACC-77004"},
        temporal_aggregates={"recent_transfer_count": 7.0},
        graph=GraphEvidence(
            adjacency={
                "ACC-77004": {"ACC-51902"},
                "ACC-51902": {"ACC-FLAGGED-2201"},
                "ACC-88231": {"ACC-77004"},
            },
            as_of_time=1_000.0,
            flagged_entities={"ACC-FLAGGED-2201"},
        ),
    )
    for name in ("rationale_accepted.json", "rationale_rejected.json"):
        rationale = json.loads((REPO_ROOT / "examples" / name).read_text(encoding="utf-8"))
        result = verifier.verify(rationale, evidence)
        print(f"\nStage 3 on {name}: V = {result.status} ({'accepted' if result.accepted else 'rejected'})")
        for reason in result.failure_reasons:
            print(f"    - {reason}")

    # ---- Grammar mask ----------------------------------------------------
    grammar = RationaleGrammar(GrammarSpec.from_schema(REPO_ROOT / "schemas" / "rationale_schema.json"))
    prefix = '{"verdict":"'
    allowed = "".join(sorted(grammar.allowed_characters(prefix)))
    print(f"\nGrammar mask after {prefix!r}: allowed next characters = {allowed!r}")
    print("  (only the first letters of the three permitted verdict labels)")

    # ---- Stage 4: mixing and conformal calibration -----------------------
    mixer = IsotonicMixer().fit(MixerInputs(p_valid, None, None), y[valid])
    calibrated_test = mixer.predict(MixerInputs(p_test, None, None))
    calibrated_calib = mixer.predict(MixerInputs(p_calib, None, None))

    calibrator = SplitConformalCalibrator(alpha=0.05)
    calibration = calibrator.calibrate(calibrated_calib, y[calib])
    coverage = calibrator.evaluate_coverage(calibrated_test, y[test])
    print("\nStage 4 split-conformal (alpha=0.05):")
    print(f"  threshold={calibration.threshold:.4f}  nominal coverage={calibration.nominal_coverage:.2f}")
    print(f"  empirical test coverage={coverage['empirical_coverage']:.4f}")
    print(f"  mean prediction-set size={coverage['mean_prediction_set_size']:.3f}")

    # ---- Metrics ---------------------------------------------------------
    threshold = select_operating_threshold(y[valid], mixer.predict(MixerInputs(p_valid, None, None)))
    metrics = compute_all(y[test], calibrated_test, threshold=threshold)
    print("\nMetrics on synthetic test data (MEANINGLESS AS SCIENCE):")
    print(f"  AUPRC={metrics.auprc:.4f}  ROC-AUC={metrics.roc_auc:.4f}  "
          f"F1={metrics.f1:.4f}  MCC={metrics.mcc:.4f}")
    for warning in metrics.warnings:
        print(f"  ! {warning}")

    print(f"\n{BANNER}")
    print("Demo complete. These numbers describe random data and nothing else.")
    print(BANNER)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
